- name: printing Course info with both PLAY and TASK
  hosts: web 
  vars:
    COURSE: "ansible"
    DURATION: 10HRS
    TRAINER: Ramu
  tasks:
  - name: printing Course info with Task level vars 
    vars:
      COURSE: "Devops with aws"
      DURATION: 120HRS
      TRAINER: Siva 
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"

  - name: printing Course info with Play level vars 
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"