- name: printing Course info 
  hosts: web
  tasks:
  - name: Course Information
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }} and Trainer is {{ TRAINER }}"