- name: data types
  hosts: web 
  tasks:
  - name: data types in ansible 
    vars:
      course_name: "Devops With Aws" # string 
      DURATION: 120 # integer (number)
      topics: # list []
      - Linux
      - Shell
      - ansible
      live: true  # boolean 
      Cloud:
        ci: jenkins
        Linux: Shell
        ansible: configuring
    ansible.builtin.debug:
      msg: "course name is {{ course_name}}, Duration is {{ DURATION }}, topics are {{ topics }}, is it live {{ live }} and clouds are {{ Cloud }}"