- name: print number greater than 15 
  hosts: web 
  tasks:
  - name: print if number greater than 15 
    vars:
      my_number: 20 
    ansible.builtin.debug:
      msg: "Given {{ my_number }} is greater than 15"
    when: my_number >15