- name: install and run services
  hosts: web 
  become: yes 
  tasks:
  - name: install services 
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed 

  - name: start services
    ansible.builtin.service:
      name: "{{ item }}"
      state: start
      enabled: yes 
    loop:
      - nginx
      - gcc
      - git 