- name: ansible filters
  hosts: web 
  tasks:
  - name: undefined varaible
    ansible.builtin.debug:
      msg: "Hello {{ Person | default('Ramu') }}"

  - name: string to list conversion
    vars:
      fruits: "apple, banana, Mango"
    ansible.builtin.debug:
      msg: "{{ fruits | split(',') }}"

  - name: dict to list conversion
    vars: 
      dict:
        name: Devops
        time: 10
        age: 26
    ansible.builtin.debug:
      msg: "{{ dict | dict2items }}"

  - name: list to dict conversion
    vars:
      list:
        -  { "key": "name", "value": "Devops" }
        - { "key": "time", "value": 10 }
    ansible.builtin.debug:
      msg: "{{ list | items2dict }}"

  - name: min and max numbers
    vars:
      list: [ 1, 30, 40, 60]
    ansible.builtin.debug:
      msg: "Min num is {{ list | min }} and max num is {{ list | max }}"
  - name: upper to lower 
    name: RAMU GORLA 
    ansible.builtin.debug:
      msg: "{{ name: lower }}"

  - name: lower  to upper 
    name: yadav gorla
    ansible.builtin.debug:
      msg: "{{ name: upper }}"