- name: shell and CMD module 
  hosts: web
  tasks:
  - name: shell cmd 
    ansible.builtin.shell: ls -l > /tmp/out.txt
    rigister: result_ouput

    ansible.builtin.debug:
      msg: "{{ result_ouput }}"