- name: shell and command module 
  hosts: web
  tasks:
  - name: shell command 
    ansible.builtin.shell: ls -l > /tmp/out.txt
    register: result_ouput

    ansible.builtin.debug:
      msg: "{{ result_ouput }}"