- name: shell and command module 
  hosts: local
  connection: local
  tasks:
  - name: modules runing  
    ansible.builtin.shell: ls -lt > /tmp/output.txt 
    #ansible.builtin.command: ls -lt > /tmp/output.txt 

  - name: execute ls command in command module
    #ansible.builtin.command: ls -ltr > /tmp/output.txt
    #ansible.builtin.command: ls -ltr # rc=0  (Return Code) exit code
    ansible.builtin.command: lsss -ltrssfff  #rc = 2 
    register: command_result

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_result }}"